import type { Event, Character, MultiverseTimeline } from "./types"

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Captain America: The First Avenger",
    year: 1943,
    description: "Steve Rogers becomes Captain America and fights against HYDRA during World War II.",
    location: "Europe",
    characters: ["Steve Rogers", "Peggy Carter", "Bucky Barnes", "Red Skull"],
    type: "Canon",
    universe: "Earth-199999",
  },
  {
    id: "2",
    title: "Captain Marvel",
    year: 1995,
    description: "Carol Danvers returns to Earth and discovers her true identity while fighting the Skrulls.",
    location: "Earth",
    characters: ["Carol Danvers", "Nick Fury", "Talos"],
    type: "Canon",
    universe: "Earth-199999",
  },
  {
    id: "3",
    title: "Iron Man",
    year: 2008,
    description: "Tony Stark builds the first Iron Man suit after being captured by terrorists.",
    location: "Afghanistan/USA",
    characters: ["Tony Stark", "Pepper Potts", "James Rhodes"],
    type: "Canon",
    universe: "Earth-199999",
  },
  {
    id: "4",
    title: "The Avengers",
    year: 2012,
    description: "The Avengers assemble for the first time to stop Loki and the Chitauri invasion of New York.",
    location: "New York",
    characters: ["Tony Stark", "Steve Rogers", "Thor", "Bruce Banner", "Natasha Romanoff", "Clint Barton", "Loki"],
    type: "Canon",
    universe: "Earth-199999",
  },
  {
    id: "5",
    title: "Guardians of the Galaxy",
    year: 2014,
    description: "A group of intergalactic criminals must work together to stop Ronan from using the Power Stone.",
    location: "Xandar",
    characters: ["Peter Quill", "Gamora", "Drax", "Rocket", "Groot"],
    type: "Canon",
    universe: "Earth-199999",
  },
  {
    id: "6",
    title: "Avengers: Infinity War",
    year: 2018,
    description: "The Avengers and their allies attempt to defeat Thanos before he collects all six Infinity Stones.",
    location: "Earth/Titan/Wakanda",
    characters: ["Tony Stark", "Steve Rogers", "Thor", "Bruce Banner", "Natasha Romanoff", "Thanos"],
    type: "Canon",
    universe: "Earth-199999",
  },
  {
    id: "7",
    title: "Avengers: Endgame",
    year: 2023,
    description: "The remaining Avengers devise a plan to reverse Thanos' actions and restore balance to the universe.",
    location: "Earth/Various Time Periods",
    characters: ["Tony Stark", "Steve Rogers", "Thor", "Bruce Banner", "Natasha Romanoff", "Clint Barton", "Thanos"],
    type: "Canon",
    universe: "Earth-199999",
  },
  {
    id: "8",
    title: "Spider-Man: No Way Home",
    year: 2023,
    description:
      "Peter Parker seeks Doctor Strange's help to make people forget he's Spider-Man, accidentally opening the multiverse.",
    location: "New York",
    characters: ["Peter Parker", "Doctor Strange", "MJ", "Ned Leeds"],
    type: "Canon",
    universe: "Earth-199999",
  },
  {
    id: "9",
    title: "Loki Season 1",
    year: 2023,
    description: "Loki is brought to the Time Variance Authority and helps them prevent a multiversal war.",
    location: "TVA/Various Timelines",
    characters: ["Loki", "Sylvie", "Mobius", "He Who Remains"],
    type: "Canon",
    universe: "Earth-199999",
  },
  {
    id: "10",
    title: "Doctor Strange in the Multiverse of Madness",
    year: 2023,
    description: "Doctor Strange protects America Chavez from Wanda Maximoff while traveling through the multiverse.",
    location: "Multiple Universes",
    characters: ["Doctor Strange", "Wanda Maximoff", "America Chavez", "Wong"],
    type: "Canon",
    universe: "Earth-199999",
  },
  {
    id: "11",
    title: "Ant-Man and the Wasp: Quantumania",
    year: 2023,
    description: "Scott Lang and Hope van Dyne explore the Quantum Realm and encounter Kang the Conqueror.",
    location: "Quantum Realm",
    characters: ["Scott Lang", "Hope van Dyne", "Kang", "Cassie Lang"],
    type: "Canon",
    universe: "Earth-199999",
  },
  {
    id: "12",
    title: "Secret Invasion",
    year: 2023,
    description:
      "Nick Fury returns to Earth to deal with a faction of Skrulls who have been infiltrating global power structures.",
    location: "Earth",
    characters: ["Nick Fury", "Talos", "G'iah", "Gravik"],
    type: "Canon",
    universe: "Earth-199999",
  },
  {
    id: "13",
    title: "What If... Thor Was an Only Child?",
    year: 2015,
    description:
      "In an alternate timeline, Thor grows up without Loki and becomes a party-loving prince who brings chaos to Earth.",
    location: "Earth",
    characters: ["Thor", "Jane Foster", "Darcy Lewis", "Captain Marvel"],
    type: "Theory",
    universe: "Earth-838",
  },
  {
    id: "14",
    title: "What If... Zombies?",
    year: 2018,
    description: "A quantum virus infects Earth's mightiest heroes, turning them into zombies.",
    location: "Earth",
    characters: ["Spider-Man", "Hope van Dyne", "Bruce Banner", "Doctor Strange"],
    type: "Theory",
    universe: "Earth-2149",
  },
  {
    id: "15",
    title: "Deadpool Joins the MCU",
    year: 2024,
    description: "Deadpool crosses over from the Fox universe into the main MCU timeline.",
    location: "Multiple Universes",
    characters: ["Deadpool", "Wolverine"],
    type: "Rumor",
    universe: "Earth-199999",
  },
]

export const mockCharacters: Character[] = [
  {
    name: "Tony Stark",
    bio: "Genius billionaire inventor who created the Iron Man suit. Founding member of the Avengers.",
    avatar: "/placeholder.svg?height=200&width=200",
    firstAppearance: 2008,
    deathYear: 2023,
    lastKnownLocation: "Earth",
    locationHistory: [
      { year: 2008, location: "USA" },
      { year: 2012, location: "New York" },
      { year: 2015, location: "Sokovia" },
      { year: 2016, location: "Germany" },
      { year: 2018, location: "Titan" },
      { year: 2023, location: "Earth" },
    ],
  },
  {
    name: "Steve Rogers",
    bio: "Super soldier from World War II who was frozen and revived in the modern era. Former leader of the Avengers.",
    avatar: "/placeholder.svg?height=200&width=200",
    firstAppearance: 1943,
    lastKnownLocation: "Timeline Branch",
    locationHistory: [
      { year: 1943, location: "Europe" },
      { year: 1945, location: "Arctic" },
      { year: 2012, location: "New York" },
      { year: 2016, location: "Wakanda" },
      { year: 2018, location: "Wakanda" },
      { year: 2023, location: "Timeline Branch" },
    ],
  },
  {
    name: "Thor",
    bio: "Asgardian god of thunder and former king of Asgard. Founding member of the Avengers.",
    avatar: "/placeholder.svg?height=200&width=200",
    firstAppearance: 2011,
    lastKnownLocation: "Space with Guardians",
    locationHistory: [
      { year: 2011, location: "New Mexico" },
      { year: 2012, location: "New York" },
      { year: 2013, location: "Asgard" },
      { year: 2015, location: "Sokovia" },
      { year: 2017, location: "Sakaar" },
      { year: 2018, location: "Nidavellir" },
      { year: 2023, location: "New Asgard" },
      { year: 2024, location: "Space with Guardians" },
    ],
  },
  {
    name: "Natasha Romanoff",
    bio: "Former Russian spy who became an agent of S.H.I.E.L.D. and a member of the Avengers.",
    avatar: "/placeholder.svg?height=200&width=200",
    firstAppearance: 2010,
    deathYear: 2023,
    lastKnownLocation: "Vormir",
    locationHistory: [
      { year: 2010, location: "USA" },
      { year: 2012, location: "New York" },
      { year: 2014, location: "Washington D.C." },
      { year: 2015, location: "Sokovia" },
      { year: 2016, location: "Germany" },
      { year: 2018, location: "Earth" },
      { year: 2023, location: "Vormir" },
    ],
  },
  {
    name: "Bruce Banner",
    bio: "Brilliant scientist who transforms into the Hulk when angered. Founding member of the Avengers.",
    avatar: "/placeholder.svg?height=200&width=200",
    firstAppearance: 2008,
    lastKnownLocation: "Earth",
    locationHistory: [
      { year: 2008, location: "USA" },
      { year: 2012, location: "New York" },
      { year: 2015, location: "Sokovia" },
      { year: 2017, location: "Sakaar" },
      { year: 2018, location: "Earth" },
      { year: 2023, location: "Earth" },
    ],
  },
  {
    name: "Peter Parker",
    bio: "Teenager from Queens who gained spider-like abilities and became Spider-Man. Mentored by Tony Stark.",
    avatar: "/placeholder.svg?height=200&width=200",
    firstAppearance: 2016,
    lastKnownLocation: "New York",
    locationHistory: [
      { year: 2016, location: "Germany" },
      { year: 2018, location: "Space/Titan" },
      { year: 2023, location: "Earth" },
      { year: 2024, location: "Europe" },
      { year: 2025, location: "New York" },
    ],
  },
  {
    name: "Doctor Strange",
    bio: "Former neurosurgeon who became the Sorcerer Supreme after a car accident led him to discover magic.",
    avatar: "/placeholder.svg?height=200&width=200",
    firstAppearance: 2016,
    lastKnownLocation: "New York Sanctum",
    locationHistory: [
      { year: 2016, location: "New York/Kamar-Taj" },
      { year: 2017, location: "New York" },
      { year: 2018, location: "Titan" },
      { year: 2023, location: "Earth" },
      { year: 2024, location: "Multiverse" },
    ],
  },
  {
    name: "Wanda Maximoff",
    bio: "Enhanced individual with reality-warping abilities. Former Avenger who became the Scarlet Witch.",
    avatar: "/placeholder.svg?height=200&width=200",
    firstAppearance: 2015,
    deathYear: 2023,
    lastKnownLocation: "Mount Wundagore",
    locationHistory: [
      { year: 2015, location: "Sokovia" },
      { year: 2016, location: "Avengers Compound" },
      { year: 2018, location: "Scotland/Wakanda" },
      { year: 2023, location: "Westview" },
      { year: 2023, location: "Mount Wundagore" },
    ],
  },
  {
    name: "Loki",
    bio: "God of Mischief and Thor's adopted brother. Has died and returned multiple times across the timeline.",
    avatar: "/placeholder.svg?height=200&width=200",
    firstAppearance: 2011,
    deathYear: 2018,
    lastKnownLocation: "TVA",
    locationHistory: [
      { year: 2011, location: "Asgard" },
      { year: 2012, location: "New York" },
      { year: 2013, location: "Asgard" },
      { year: 2017, location: "Sakaar" },
      { year: 2018, location: "Sanctuary II" },
      { year: 2023, location: "TVA" },
    ],
  },
]

export const mockMultiverse: MultiverseTimeline[] = [
  {
    id: "m1",
    name: "Earth-199999",
    description: "The main MCU timeline, also known as the Sacred Timeline.",
    characters: [
      "Tony Stark",
      "Steve Rogers",
      "Thor",
      "Natasha Romanoff",
      "Bruce Banner",
      "Peter Parker",
      "Doctor Strange",
      "Wanda Maximoff",
    ],
    events: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
    status: "active",
  },
  {
    id: "m2",
    name: "Earth-838",
    description: "An alternate universe where the Illuminati formed instead of the Avengers.",
    characters: [
      "Doctor Strange",
      "Professor X",
      "Captain Carter",
      "Black Bolt",
      "Captain Marvel",
      "Reed Richards",
      "Wanda Maximoff",
    ],
    events: ["13"],
    status: "active",
  },
  {
    id: "m3",
    name: "Earth-2149",
    description: "A universe where a quantum virus turned superheroes into zombies.",
    characters: [
      "Zombie Iron Man",
      "Zombie Captain America",
      "Zombie Doctor Strange",
      "Spider-Man",
      "Hope van Dyne",
      "Bruce Banner",
    ],
    events: ["14"],
    status: "active",
  },
  {
    id: "m4",
    name: "Loki Variant Timeline",
    description: "Timeline created when Loki escaped with the Tesseract during the Time Heist.",
    characters: ["Loki", "Sylvie", "Mobius", "He Who Remains", "Ravonna Renslayer"],
    events: ["9"],
    status: "pruned",
  },
  {
    id: "m5",
    name: "Deadpool Universe",
    description: "Universe where Deadpool and the X-Men exist, soon to merge with the main MCU.",
    characters: ["Deadpool", "Wolverine", "Colossus"],
    events: ["15"],
    status: "active",
  },
]
